import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  if (FirebaseAuth.instance.currentUser == null) {
    await FirebaseAuth.instance.signInAnonymously();
  }
  runApp(const GolfApp());
}

class GolfApp extends StatelessWidget {
  const GolfApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Golf Starter',
      theme: ThemeData(useMaterial3: true),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final _roomCtrl = TextEditingController();
  final _cf = FirebaseFunctions.instance;
  String? _status;

  Future<void> _createRoom() async {
    try {
      final res = await _cf.httpsCallable('createRoom').call({'maxPlayers': 4});
      setState(() { _status = "Room: ${res.data['roomId']} Invite: ${res.data['inviteCode']}"; });
    } catch (e) { setState(() { _status = 'Error: $e'; }); }
  }

  Future<void> _joinRoom() async {
    try {
      final id = _roomCtrl.text.trim();
      await _cf.httpsCallable('joinRoom').call({'roomId': id});
      setState(() { _status = "Joined $id"; });
    } catch (e) { setState(() { _status = 'Error: $e'; }); }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Golf — Starter')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ElevatedButton(onPressed: _createRoom, child: const Text('Create Room (callable)')),
            const SizedBox(height: 12),
            TextField(controller: _roomCtrl, decoration: const InputDecoration(labelText: 'Room ID')),
            const SizedBox(height: 8),
            ElevatedButton(onPressed: _joinRoom, child: const Text('Join Room (callable)')),
            const SizedBox(height: 16),
            Text(_status ?? 'Status: idle'),
          ],
        ),
      ),
    );
  }
}
